FROM node:14.3.0-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV=Production
COPY package.json ./
RUN npm install
#RUN npm i -g react-scripts@3.4.1
COPY . ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html/
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]