version: '3'

services:
  db-server:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root2020!
    ports:
      - "27017:27017"
    volumes:
      - /c/data/db:/data/db
    networks:
      - app-network

  backend-server:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend-server
    ports:
      - "3030:3030"
    networks:
      - app-network
    depends_on:
      - "db-server"

  frontend-server:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend-server
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - "db-server"
      - "backend-server"

networks: 
    app-network:
      driver: bridge