version: '3'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root2020!
    depends_on:
      - "db-server"
    networks:
      - app-network

  db-server:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root2020!
    ports:
      - "27017:27017"
    volumes:
      - /c/data/db:/data/db
    networks:
      - app-network

  backend-server:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend-server
    ports:
      - "3030:3030"
    networks:
      - app-network
    depends_on:
      - "db-server"

networks: 
    app-network:
      driver: bridge